services:
  redis_server:
    image: redis
    container_name: redis_server
    hostname: redis_server
    ports:
      - 6379:6379
    restart: always
    
  blockly_server:
    privileged: true
    image: chronis10/fossbot_blockly:latest
    container_name: blockly_server
    hostname: blockly_server
    ports:
      - 5000:5000
    restart: always
    volumes:
      - /home/pi/data:/app/data

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: blockly_server