name: Build Basic image

on: [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push ARM image
        uses: docker/build-push-action@v2
        
        with:       
          context: source/basic_image/
          file: source/basic_image/Dockerfile
          platforms: linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fossbot_basic:latest
  
